### ISSUE TITLE
No onboarding PR is created for tutorial steps

### ISSUE THREAD

**Issue by denis-zhdanov** [renovatebot/tutorial#25]
**Problem**

Followed [tutorial steps](https://github.com/renovatebot/tutorial/blob/main/README.md) - forked tutorial project ([link](https://github.com/denis-zhdanov/renovate-tutorial) and installed renovate app but no onboarding PR was created.

Tried to reinstall renovate app but it didn't help

**Comment by rarkins** [comment]
Did you take note of these steps to do "Select repositories" instead of "All repositories"?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/6311784/229583010-8dd77ac6-010d-4850-b293-19a95eb31340.png">

If you instead selected "All repositories", set `forkProcessing=enabled` instead of `includeFork=true`. The old name `includeForks=true` should also work (note the additional `s` compared to yours).

**Comment by denis-zhdanov** [comment]
yes, I did follow the steps and selected the forked repo. That repo is shown in renovate dashboard as well, you can check that easily from renovate side - https://app.renovatebot.com/dashboard#github/denis-zhdanov/renovate-tutorial

**Comment by Eeebru** [comment]
I am having this same problem. I selected the forked repo, but while searching I saw this on Renovate's documentation page:

![Screenshot 2023-04-05 at 13 23 18](https://user-images.githubusercontent.com/54288773/230079267-c527c7d1-4955-40b6-8dc7-e5e7d2d902ba.png)

Pretty confusing instruction there.

**Comment by rarkins** [comment]
Renovate will ignore forks by default if you choose "All repositories". It will process forks is you choose "Select repositories". The last sentence refers to GitHub's limitation, not Renovate's, and can be removed if people get confused.

**Comment by denis-zhdanov** [comment]
@rarkins [renovate tutorial](https://github.com/renovatebot/tutorial/blob/main/README.md) explicitly provides steps as `Let’s start by forking the tutorial repo to your account, installing the Renovate GitHub App`. It doesn't look good if product's tutorial is incorrect :)

**Comment by rarkins** [comment]
It's not incorrect. The tutorial tells you to use "Select repositories" when installing the app and then to fork the repo.

**Comment by Eeebru** [comment]
@rarkins That was a simple instruction to follow, I wouldn't be here if it has worked has it should. I selected the only the forked repo, and didn't get a the onboarding PR. I have selected a few other repos, it still didn't work.

**Comment by rarkins** [comment]
@Eeebru according to GitHub's API, you first installed with All repositories (there were 110 total) and then only after that it looks like you modified the installation to be Select repositories (4 total). Your first action of installing with All repositories resulted in all your forked repositories being marked as disabled in Renovate's backend.

**Comment by denis-zhdanov** [comment]
```
It's not incorrect. The tutorial tells you to use "Select repositories" when installing the app and then to fork the repo.
```

what's the reason to ask forking the renovate repo then? :)
