### ISSUE TITLE
Onboarding PR already exists but cannot find it. It was probably created by a different user. 

### ISSUE THREAD

**Issue by bodote** [renovatebot/tutorial#39]
As a newbee with renovate, but after finishing the tutorial, I tried to add one of my repos (https://github.com/bodote/bodote.github.io)  to my "selected repository list" for renovate. 
But renovate did not generate the initial PR because : 

```
INFO: Repository started
{
  "renovateVersion": "37.0.3"
}

INFO: Branch created (branch="renovate/configure")
{
  "commit": "45c355e22b99489021f1447c98f084809dfaebcc"
  "onboarding": true
}

INFO: Dependency extraction complete
{
  "baseBranch": "master"
  "stats": {
    "managers": {
      "bundler": {
        "fileCount": 1,
        "depCount": 10
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 10
    }
  }
}

WARN: Onboarding PR already exists but cannot find it. It was probably created by a different user.
INFO: Repository finished
{
  "cloned": true
  "durationMs": 16367
}
```
What can be done in that case to force renovate to generate the  Onboarding PR anyway?

**Comment by rarkins** [comment]
Uninstall the hosted bot if you don't want to use it. Then close and rename the existing PR which the bot created.

**Comment by bodote** [comment]
hm , don't realy understand why, but after I just "run renovate" again on the same project, it finally generated the onboarding PR as expected.
